### ISSUE TITLE
静态资源是否可以传到cdn

### ISSUE THREAD

**Issue by tza17313** [serverless-components/tencent-nextjs#10]
`npm run build` 生成的 `.next/static` 下的文件是否可以结合`tencent-cos`组件上传到对象存储中？

**Comment by tinafangkunding** [comment]
可以的，可以参考这个教程 https://yugasun.com/post/serverless-nextjs.html，通过 cos 托管静态资源，并且可以通过 cdn 加速

**Comment by tza17313** [comment]
@tinafangkunding 
感谢，教程写的很详细
